name: booklibrary2020
description: A book library for handsome guys.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

# An awesome list that curates the best Flutter libraries, tools, tutorials, articles and more.
# https://github.com/Solido/awesome-flutter

# Design
# Flutter Material Theme editor
# https://github.com/rxlabz/panache
# Play with colors in flutter
# https://github.com/bregydoc/pigment


# Extensions method
# https://pub.dev/packages/dart_extensions
# https://pub.dev/packages/dartx
# https://pub.dev/packages/collection_ext
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # https://pub.dev/packages/flappy_search_bar#
  flappy_search_bar: ^1.7.2

  # https://pub.dev/packages/flutter_rating_bar
  flutter_rating_bar: 3.0.1

  # Easy localization
  # https://pub.dev/packages/easy_localization
  easy_localization: 2.1.0+2

  # copy_with_extension_gen
  # https://pub.dev/packages/copy_with_extension_gen
  copy_with_extension_gen: 1.1.0

  #Bloc
  #https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^3.2.0

  #Date time format
  intl: ^0.16.1

  # https://pub.dev/packages/dart_extensions
  dart_extensions: 1.0.0

  #Network
  #https://pub.dev/packages/dio
  dio: ^3.0.9
  #https://pub.dev/packages/dio_flutter_transformer
  dio_flutter_transformer: ^3.0.2
  #https://pub.dev/packages/alice
  alice: ^0.0.28
  #https://pub.dev/packages/pretty_dio_logger
  pretty_dio_logger: ^1.1.1
  #https://pub.dev/packages/retrofit
  retrofit: ^1.3.3

  #Equatable
  #https://pub.dev/packages/equatable
  equatable: ^1.1.1

  #Event bus
  #https://pub.dev/packages/event_bus
  event_bus: ^1.1.1

  #cached_network_image
  #https://pub.dev/packages/cached_network_image
  cached_network_image: ^2.1.0+1

  # keyboard_visibility
  # https://pub.dev/packages/keyboard_visibility
  keyboard_visibility: ^0.5.6

    #IMEI
  #https://pub.dev/packages/imei_plugin
  #imei_plugin: ^1.1.0
  #shared_preferences https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.6+3

  # Icon
  # https://materialdesignicons.com/
  community_material_icon: ^3.5.95

  # Crash report
  sentry: ^3.0.1

  # https://pub.dev/packages/date_range_picker
  # date_range_picker: ^1.0.6

  # https://pub.dev/packages/configurable_expansion_tile
  # configurable_expansion_tile: ^1.0.0
  # https://pub.dev/packages/grouped_buttons
  # grouped_buttons: ^1.0.4


  # https://pub.dev/packages/uuid
  # uuid: ^2.0.4
  # https://pub.dev/packages/package_info
  # package_info: ^0.4.0+16
  # https://pub.dev/packages/device_info
  # device_info: ^0.4.2+1
  # https://pub.dev/packages/crypto
  # crypto: ^2.1.4

  # https://pub.dev/packages/encrypt
  # encrypt: ^4.0.0
  # https://pub.dev/packages/encrypt

  convert: ^2.1.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dependency_overrides:
  rxdart: ^0.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.3.3
  build_runner:  ^1.8.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
